# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oni_model', '0004_auto_20150328_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesspoint',
            name='sys_os_name',
        ),
        migrations.RemoveField(
            model_name='accesspoint',
            name='sys_os_type',
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='device_architecture',
            field=models.TextField(null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='device_board',
            field=models.TextField(null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='device_cpu',
            field=models.TextField(null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='device_memory_available',
            field=models.IntegerField(null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='device_memory_free',
            field=models.IntegerField(null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='firmware_build',
            field=models.TextField(null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='firmware_install_timestamp',
            field=models.DateField(null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='firmware_release_name',
            field=models.TextField(null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='firmware_release_version',
            field=models.TextField(null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='firmware_type',
            field=model_utils.fields.StatusField(default='OpenWrt', max_length=100, null=True, no_check_for_status=True, choices=[(0, 'dummy')]),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='olsrd_main_ip',
            field=models.TextField(null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='olsrd_running',
            field=models.NullBooleanField(),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='opennet_certificate_cn',
            field=models.TextField(null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='opennet_id',
            field=models.TextField(null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='opennet_install_timestamp',
            field=models.DateField(null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='opennet_packages',
            field=models.TextField(null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='opennet_service_relay_connected',
            field=models.NullBooleanField(),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='opennet_service_relay_enabled',
            field=models.NullBooleanField(),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='opennet_services_sorting',
            field=model_utils.fields.StatusField(default='manuel', max_length=100, null=True, no_check_for_status=True, choices=[(0, 'dummy')]),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='opennet_version',
            field=models.TextField(null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='opennet_vpn_internet_autosearch',
            field=models.TextField(null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='opennet_vpn_internet_blacklist',
            field=models.TextField(null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='opennet_vpn_internet_connections',
            field=models.TextField(null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='opennet_vpn_internet_enabled',
            field=models.NullBooleanField(),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='opennet_vpn_internet_gateways',
            field=models.TextField(null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='opennet_vpn_mesh_connected',
            field=models.NullBooleanField(),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='opennet_vpn_mesh_connections',
            field=models.TextField(null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='opennet_vpn_mesh_gateway_names',
            field=models.TextField(null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='opennet_vpn_mesh_gateways',
            field=models.TextField(null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='opennet_wifidog_enabled',
            field=models.NullBooleanField(),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='opennet_wifidog_id',
            field=models.TextField(null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='system_kernel',
            field=models.TextField(null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='system_load_15min',
            field=models.FloatField(null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='system_load_1min',
            field=models.FloatField(null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='system_load_5min',
            field=models.FloatField(null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='system_uptime',
            field=models.IntegerField(null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='system_watchdog_enabled',
            field=models.NullBooleanField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='antenna',
            field=models.TextField(null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='device_model',
            field=models.TextField(null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='owner',
            field=models.TextField(null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='post_address',
            field=models.TextField(null=True),
            preserve_default=True,
        ),
    ]
