# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oni_model', '0014_auto_20170920_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkInterfaceAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField()),
                ('family', model_utils.fields.StatusField(choices=[('inet', 'IPv4'), ('inet6', 'IPv6')], default='inet', max_length=100, no_check_for_status=True)),
                ('netmask_prefixlen', models.IntegerField()),
            ],
            managers=[
                ('get_by_ipaddress', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='ethernetnetworkinterface',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='ethernetnetworkinterface',
            name='ip_broadcast',
        ),
        migrations.RemoveField(
            model_name='ethernetnetworkinterface',
            name='ip_label',
        ),
        migrations.AddField(
            model_name='networkinterfaceaddress',
            name='interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='oni_model.EthernetNetworkInterface'),
        ),
    ]
