# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oni_model', '0015_auto_20171018_1735'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='networkinterfaceaddress',
            managers=[
            ],
        ),
    ]
