# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 01:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oni_model', '0016_auto_20171018_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ethernetnetworkinterface',
            old_name='access_point',
            new_name='accesspoint',
        ),
    ]
