# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-20 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oni_model', '0017_auto_20171022_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethernetnetworkinterface',
            name='ifstat_collisions',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ethernetnetworkinterface',
            name='ifstat_multicast',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ethernetnetworkinterface',
            name='ifstat_rx_bytes',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ethernetnetworkinterface',
            name='ifstat_rx_compressed',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ethernetnetworkinterface',
            name='ifstat_rx_crc_errors',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ethernetnetworkinterface',
            name='ifstat_rx_dropped',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ethernetnetworkinterface',
            name='ifstat_rx_errors',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ethernetnetworkinterface',
            name='ifstat_rx_fifo_errors',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ethernetnetworkinterface',
            name='ifstat_rx_frame_errors',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ethernetnetworkinterface',
            name='ifstat_rx_length_errors',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ethernetnetworkinterface',
            name='ifstat_rx_missed_errors',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ethernetnetworkinterface',
            name='ifstat_rx_over_errors',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ethernetnetworkinterface',
            name='ifstat_rx_packets',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ethernetnetworkinterface',
            name='ifstat_tx_aborted_errors',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ethernetnetworkinterface',
            name='ifstat_tx_bytes',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ethernetnetworkinterface',
            name='ifstat_tx_carrier_errors',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ethernetnetworkinterface',
            name='ifstat_tx_compressed',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ethernetnetworkinterface',
            name='ifstat_tx_dropped',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ethernetnetworkinterface',
            name='ifstat_tx_errors',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ethernetnetworkinterface',
            name='ifstat_tx_fifo_errors',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ethernetnetworkinterface',
            name='ifstat_tx_heartbeat_errors',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ethernetnetworkinterface',
            name='ifstat_tx_packets',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ethernetnetworkinterface',
            name='ifstat_tx_window_errors',
            field=models.BigIntegerField(null=True),
        ),
    ]
