# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-16 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oni_model', '0018_auto_20180120_0402'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPointSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesspoints', to='oni_model.AccessPointSite'),
        ),
    ]
