# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-10 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oni_model', '0019_auto_20190316_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspoint',
            name='main_ipv6',
            field=models.GenericIPAddressField(null=True, protocol='IPv6'),
        ),
    ]
